### PR TITLE
feat(structslop): add support for structslop

### PR DESCRIPTION
**Pull request by adambabik**
More about structslop: https://github.com/orijtech/structslop

### CODE REVIEW

**Review by TekWizely — CHANGES_REQUESTED** [review]
Greetings and thanks for taking the time to create a PR!

I've been following the release of structsop so its cool to see this integration request.

Regarding the PR's impl types ie `mod`, `repo-mod`, and `repo-pkg`:

The project page sates : 

> You can run structslop either on a Go package or Go files, the same way as other Go tools work.
> Example:
> ```
> $ structslop github.com/orijtech/structslop/testdata/src/struct
> ```
> or:
> ```
> $ structslop ./testdata/src/struct/p.go
> ```

There's no direct statement of `module`-level support.

One way to confirm this is to create a module / sub-module file structure (ie sub modules have their own go.mod file) with changes in the child module that should be reported.   Then run the tool within the parent module and confirm whether or not it reports the child module errors.

If it does, then it doesn't honor module boundaries.

My guess is this tool behaves similar to `gofmt` in that its generally file based, but checks all files recursively when given a directory/package as an argument.

If thats true, then the correct imps for this would be:

* file: `go-strucslop` : executes `structslop <file>` against staged file(s) directly
* repo: `go-structslop-repo` : executes `structslop .` against repo root folder

Lemme know what you think and maybe also share some deets on how you're actually using it in your local dev?

Also, I've cc'd @cuonglm to give them a chance to chime in.

Thanks again and I look forward to integrating this PR !

-TW

**Comment by TekWizely** [comment]
@adambabik Not sure if you saw these recent comments?

**Comment by adambabik** [comment]
Thanks for the reply. Sorry, I didn't have time to look at this earlier.

> One way to confirm this is to create a module / sub-module file structure (ie sub modules have their own go.mod file) with changes in the child module that should be reported. Then run the tool within the parent module and confirm whether or not it reports the child module errors.

I just checked and it does not reports errors in the child module.

Additionally, passing a single file like `structslop ./testdata/src/struct/p.go` also might not work if that file uses types from other files in the same package. I am not sure how consistent is that with other tools supported here but it seems like the only implementation behaving consistently is `go-structslop-repo`.

**Comment by TekWizely** [comment]
Hey again !

OK so I've also taken a few minutes to checkout the repo and play with a few module and pkg configurations.

I've come to agree with you on the single-file usage as a single file is almost never fully-sufficient to check against.

I first thought it would likely behave like `gofmt`, but it looks like it actually behaves similarly to the builtin `go build` and `go test` tools.  As such, the following types should probably be supported:

| Hook ID            | Description
|--------------------|------------
| `go-strucslop-mod`      | Run `'cd $(mod_root $FILE); strucslop [$ARGS] ./...'` for each staged .go file
| `go-strucslop-pkg`      | Run `'strucslop [$ARGS] ./$(dirname $FILE)'` for each staged .go file
| `go-strucslop-repo-mod` | Run `'cd $(mod_root); strucslop [$ARGS] ./...'` for each module in the repo
| `go-strucslop-repo-pkg` | Run `'strucslop [$ARGS] ./...'` in repo root folder

Could you please add `go-structslop-pkg` to your PR?

**Comment by adambabik** [comment]
@TekWizely I applied the changes, please review again. One note, I put `-apply` flag by default. It should much default behaviour of other tools like `revive`.

**Review by TekWizely — CHANGES_REQUESTED** [review]
Hey!  Okay I think we're really close ...

> It should m[at]ch default behaviour of other tools like revive.

Honestly I don't believe that revive modifies code at all - I can't find any documentation to suggest it does?

Regardless ... I've been grinding on the idea of defaulting to `--apply` ... 

Generally, I prefer to leave decisions like that up to the user, and I did go out of my way to design a pattern that lets users pass arguments to the hooks .. So my general preference would be to have the user use `args: [ '--apply' ]` in their hook definition.

That being said ...

Checking the structlsop documentation, I see that there does not _currently_ appear to be a way to bypass structslop reports for a given struct. i.e. some kind of `//structslop:ignore`.  Without that kind of support, the user is likely to be overloaded with structslop warnings over time unless they are committed to re-orging their structs.

 Q: Is there an argument the user could pass to `undo` the apply argument?

I think the way forward is one of two options:
* Remove the `--apply` and add a note about is a useful argument in the hook documentation (there are patterns for this relating to hooks with `--fix` support)
* Rename the hooks to `*-structslop-fix-*` to make it clear that they contain an auto-fix flag.  This will clarify the behavior to the user and leave room for a non `-fix` version of the hooks in the future if some kind of ignore flag support is added.

I'll leave the decision of which way to go up to you as its your PR and I'm really glad to have your contribution.

Lemme know what you think!

-TW

**Comment by adambabik** [comment]
> Honestly I don't believe that revive modifies code at all - I can't find any documentation to suggest it does?

You're right, I had more hooks set up which did the job.

> Generally, I prefer to leave decisions like that up to the user, and I did go out of my way to design a pattern that lets users pass arguments to the hooks .. So my general preference would be to have the user use `args: [ '--apply' ]` in their hook definition.

I checked `gofmt` and `gofumpt` which actually follow that logic so I will remove `-apply` to be consistent.

> Checking the structlsop documentation, I see that there does not _currently_ appear to be a way to bypass structslop reports for a given struct. i.e. some kind of `//structslop:ignore`. Without that kind of support, the user is likely to be overloaded with structslop warnings over time unless they are committed to re-orging their structs.

Yes, I noticed this issue. The other thing that bothers me is that `structslop` does not provide a way to ignore generated files (it makes sense to reformat generated files too if you care about the speed but I'd like to have a choice). I will likely follow up in `structslop` repo to implement these two things.

> I'll leave the decision of which way to go up to you as its your PR and I'm really glad to have your contribution.

As described above, I will move forward and remove `-apply`.

**Review by TekWizely — CHANGES_REQUESTED** [review]
HOWDY !

I have several final, mostly small, notes, but I can work on implementing them(looks like you enabled maintainer edits, thanks!)

In addition to the notes, we also need to:

* Add the hook ids to the [sample-config.yaml](https://github.com/TekWizely/pre-commit-golang/blob/master/sample-config.yaml) file.  Pretty much the same as the sample file in the Readme:
    ```
    # StatiCheck ...
    
    #
    # StructSlop
    #
    -   id: go-structslop-mod
    -   id: go-structslop-pkg
    -   id: go-structslop-repo-mod
    -   id: go-structslop-repo-pkg
    
    # Formatters ...
    ```
* Add a link the [Hooks](https://github.com/TekWizely/pre-commit-golang#hooks) section of the Readme.
I guess we need to decide if structslop is a _"correctness checker"_ or a _"style checker"_ ?  I'm going to go with _"correctness checker"_ methinks ...

NOTE: If you do plan on making changes, keep an eye out for my changes as you may have to do a pull/merge

Thanks, looking forward to merging this.

-TW

PS: I should probably figure out some form of new hook template / check-list - I'll grind on that ...

**Comment by TekWizely** [comment]
Merged - Thanks @adambabik !

cc: @orijtech

**Pull request merged**
